import { Karla } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const karla = Karla({
  weight: ['200', '300', '400', '500'],
  subsets: ["latin"],
  display: "swap"
});

const spaceGrotesk = Space_Grotesk({
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"],
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <body className={karla.className + ' ' + spaceGrotesk.className}>
        {children}
      </body>
    </>
  );
}